package launcher

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// ResolveMaven finds the mvn binary (mvn.cmd on Windows via PATHEXT).
func ResolveMaven() (string, error) {
	p, err := exec.LookPath("mvn")
	if err != nil {
		return "", fmt.Errorf("mvn not found in PATH (install Maven, or use launcher=jar)")
	}
	return p, nil
}

// BuildMavenCommand: mvn spring-boot:run with JVM options and app args via
// the plugin's space-separated single-string properties (args containing
// spaces are unsupported).
func BuildMavenCommand(mvnBin string, jvmOpts, args []string) *exec.Cmd {
	argv := []string{"spring-boot:run"}
	if s := strings.Join(jvmOpts, " "); s != "" {
		argv = append(argv, "-Dspring-boot.run.jvmArguments="+s)
	}
	if s := strings.Join(args, " "); s != "" {
		argv = append(argv, "-Dspring-boot.run.arguments="+s)
	}
	return exec.Command(mvnBin, argv...)
}

// ResolveGradle prefers the project wrapper (gradlew/gradlew.bat) in workdir,
// else gradle from PATH.
func ResolveGradle(workdir string) (string, error) {
	wrapper := "gradlew"
	if runtime.GOOS == "windows" {
		wrapper = "gradlew.bat"
	}
	cand := filepath.Join(workdir, wrapper)
	if st, err := os.Stat(cand); err == nil && !st.IsDir() {
		return cand, nil
	}
	if p, err := exec.LookPath("gradle"); err == nil {
		return p, nil
	}
	return "", fmt.Errorf("gradle not found: no %s in workdir and no gradle in PATH", wrapper)
}

// GradleInitScript renders the init script injecting jvmArgs into any bootRun
// task (duck-typed: the Spring Boot gradle plugin classes are not on the init
// script classpath). Existing bootRun.jvmArgs from the build script are
// replaced — JVM options are owned by spm4a (§8.4).
func GradleInitScript(jvmOpts []string) string {
	quoted := make([]string, len(jvmOpts))
	for i, o := range jvmOpts {
		quoted[i] = groovyQuote(o)
	}
	return `// generated by spm4a; overwritten on every start
allprojects { project ->
    project.tasks.matching { it.name == 'bootRun' }.configureEach { task ->
        if (task.hasProperty('jvmArgs')) {
            task.jvmArgs = [` + strings.Join(quoted, ", ") + `]
        }
    }
}
`
}

// BuildCustomCommand runs the user's argv in workdir. A command[0] containing
// a path separator (or starting with ".") resolves against workdir; a bare
// name goes through PATH lookup.
func BuildCustomCommand(command []string, workdir string) (*exec.Cmd, error) {
	if len(command) == 0 {
		return nil, fmt.Errorf("command is required for launcher=custom")
	}
	bin := command[0]
	if strings.ContainsAny(bin, `/\`) || strings.HasPrefix(bin, ".") {
		bin = filepath.Join(workdir, filepath.FromSlash(bin))
	} else {
		p, err := exec.LookPath(bin)
		if err != nil {
			return nil, fmt.Errorf("command not found: %s", bin)
		}
		bin = p
	}
	cmd := exec.Command(bin, command[1:]...)
	return cmd, nil
}

// BuildGradleCommand: gradle bootRun [-I initscript] [--args=...].
func BuildGradleCommand(gradleBin string, args []string, initScript string) *exec.Cmd {
	argv := []string{"bootRun"}
	if initScript != "" {
		argv = append(argv, "-I", initScript)
	}
	if s := strings.Join(args, " "); s != "" {
		argv = append(argv, "--args="+s)
	}
	return exec.Command(gradleBin, argv...)
}

// groovyQuote produces a Groovy single-quoted string literal.
func groovyQuote(s string) string {
	return "'" + strings.ReplaceAll(strings.ReplaceAll(s, `\`, `\\`), `'`, `\'`) + "'"
}
